# _config.yml
title: ReinierTutoriales
baseurl: "/webReinierTutoriales"  # Nombre de tu repositorio
url: "https://reiniertutoriales.github.io"
theme: minima
permalink: /:categories/:title/
collections:
  posts:
    output: true
