name: Actualizar API Cache

on:
  schedule:
    - cron: '0 * * * *'  # Ejecuta cada hora
  workflow_dispatch:

jobs:
  update-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Ejecutar script para actualizar API
        run: node scripts/update-api.js
      - name: Hacer commit de los cambios
        run: |
          git config --global user.email "tu-email@example.com"
          git config --global user.name "TuNombre"
          git add data/api.json
          git commit -m "Actualización automática de API"
          git push
