name: Generar y Desplegar Contenido

on: [push]

# Agrega permisos explícitos para el GITHUB_TOKEN
permissions:
  contents: write  # Permite escribir en el repositorio
  pages: write    # Permite actualizar GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Verificar existencia de secreto
        id: check-secret
        run: |
          if [ -z "${{ secrets.MI_TOKEN }}" ]; then
            echo "::error::El secreto MI_TOKEN no está configurado"
            exit 1
          else
            echo "Secreto detectado (valor oculto por seguridad)"
          fi

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Obtener artículos de la API de GitHub
        if: steps.check-secret.outcome == 'success'
        run: |
          curl -H "Authorization: token ${{ secrets.MI_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/ReinierTutoriales/webReinierTutoriales/contents/_posts > posts.json
          jq '[.[] | select(.name | endswith(".md")) | {name: .name, download_url: .download_url}]' posts.json > articles.json
        env:
          GITHUB_TOKEN: ${{ secrets.MI_TOKEN }}

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
